### PR TITLE
Fix/fix monthly digest workers

### LINKED ISSUE #294: Refactor monthly digest email worker
When we implemented generalized workers for email on #276 we left behind a bug.

We spawn a worker for an entire community. Which means that, if a email for a single user in that community fails, the entire worker fails. This also can cause some users to receive the same message multiple times, since the worker will retry sending emails to the entire community up to 3 times.

We should change this behavior to spawn a worker for every member, instead of a worker for every community.

### PR DESCRIPTION
**Pull request by MatheusBuss**
## What issue does this PR close
Closes #294 

## Changes Proposed ( a list of new changes introduced by this PR)
Refactor Monthly Digest Worker to make it so that an individual worker is responsible for an individual user, instead of a single worker being responsible for the entire community.

## How to test ( a list of instructions on how to test this PR)
Run `mix test`

### CODE REVIEW

File: lib/cambiatus/workers/monthly_digest_worker.ex [hunk 1]
```diff
@@ -1,23 +1,39 @@
...
+      Community
+      |> Community.with_news_enabled()
+      |> Repo.all()
+      |> Repo.preload([
+        [news: News.last_thirty_days()],
+        [members: User.accept_digest()],
+        :subdomain
+      ])
+      |> Enum.filter(&Enum.any?(&1.news))
+      |> Enum.reduce(multi, fn community, multi ->
```
Comment (NeoVier) [inline lib/cambiatus/workers/monthly_digest_worker.ex:27]: I think this would be a bit clearer - we wouldn't have so many `multi` around:

```suggestion
      |> Enum.reduce(Multi.new(), fn community, multi ->
```

File: lib/cambiatus_web/email.ex [hunk 2]
```diff
@@ -41,14 +42,15 @@ defmodule CambiatusWeb.Email do
...
-  # input is a community with preloaded news with less than 30 days and members with active digest
-  def monthly_digest(community) do
-    Enum.each(community.members, fn member ->
-      compose_email_headers(member, community)
-      |> subject("#{community.name} - " <> gettext("Community News"))
-      |> render_body("monthly_digest.html", render_params(member, community))
-      |> Mailer.deliver()
-    end)
+  # input is a community and a user
+  # community and memebr filtering is done by the MonthlyDigestWorker
```
Comment (NeoVier) [inline lib/cambiatus_web/email.ex:46]:
```suggestion
  # community and member filtering is done by the MonthlyDigestWorker
```

**Review by NeoVier — APPROVED** [review]

File: lib/cambiatus_web/email.ex (hunk 2 above)
Comment (MatheusBuss) [reply lib/cambiatus_web/email.ex:46]: Oops! Nice catch

File: lib/cambiatus/workers/monthly_digest_worker.ex (hunk 1 above)
Comment (MatheusBuss) [reply lib/cambiatus/workers/monthly_digest_worker.ex]: More concise indeed

**Review by lucca65 — APPROVED** [review]
✅
