### PR TITLE
Fix/rich link empty bio

### LINKED ISSUE #264: Prevent a nil bio field to crash rich link rendering
Currently if a user's bio field is stored as `nil` it will be passed to the function `md_to_txt/1` in `lib/cambiatus_web/rich_link_view.exs` and crash it.

This behavior should be fixed.

### PR DESCRIPTION
**Pull request by MatheusBuss**
## What issue does this PR close
Closes #264 

## Changes Proposed ( a list of new changes introduced by this PR)
Fill rich link description field when the user has no bio

### CODE REVIEW

File: lib/cambiatus_web/controllers/rich_link_controller.ex [hunk 1]
```diff
@@ -83,40 +87,36 @@ defmodule CambiatusWeb.RichLinkController do
...
-       }}
-    else
-      {:error, reason} ->
-        {:error, reason}
-    end
-  end
+  def category_rich_link(category_id, community, language) do
+    case Cambiatus.Shop.get_category(category_id) do
+      nil ->
+        {:error, "Category not found"}
```
Comment (MatheusBuss) [inline lib/cambiatus_web/controllers/rich_link_controller.ex:93]: @lucca65 maybe we should make `Cambiatus.Shop.get_category` consistent with other get functions, as in make it return either `{:ok, category}` or `{:error, reason}`

File: lib/cambiatus_web/controllers/rich_link_controller.ex [hunk 2]
```diff
@@ -83,40 +87,36 @@ defmodule CambiatusWeb.RichLinkController do
...
+    {:ok,
+     %{
+       type: :community,
+       description: community.description,
+       title: community.name,
+       url: community.subdomain.name,
+       image: community.logo,
+       locale: get_language(language, %{})
+     }}
+  end
```
Comment (MatheusBuss) [inline lib/cambiatus_web/controllers/rich_link_controller.ex:118]: Since I'm revisiting this, it could be a good idea to set the community language properly. We could make it get the community creator language or have some way to set a default language for every community.

File: lib/cambiatus_web/controllers/rich_link_controller.ex [hunk 3]
```diff
@@ -44,37 +46,39 @@ defmodule CambiatusWeb.RichLinkController do
...
+        {:ok,
+         %{
+           type: :product,
+           description: product.description,
+           title: product.title,
+           url: community.subdomain.name <> "/shop/#{product.id}",
+           image: if(images != [], do: Map.get(List.first(images), :uri), else: @fallback_image),
+           locale: get_language(language, creator),
+           price: product.price,
+           currency: String.slice(community.symbol, 2, 7),
```
[the remark this answers is not in the document]
Comment (NeoVier) [reply lib/cambiatus_web/controllers/rich_link_controller.ex:63]: The current implementation actually wouldn't work for this community I have: https://precisionthree.staging.cambiatus.io/dashboard. The symbol is 7 characters long (`3,THREEPR`)

[the remark this answers is not in the document]
Comment (MatheusBuss) [reply lib/cambiatus_web/controllers/rich_link_controller.ex:63]: This makes a lot of sense actually. I thought we had some limit to the symbol string. Good catch!

**Review by NeoVier — APPROVED** [review]
✨

File: lib/cambiatus_web/controllers/rich_link_controller.ex (hunk 3 above)
[the remark this answers is not in the document]
Comment (NeoVier) [reply lib/cambiatus_web/controllers/rich_link_controller.ex]: We do have some limits, I think it must be 3 <= length <= 7. But we don't need to worry about that with the `String.split` method

File: lib/cambiatus_web/controllers/rich_link_controller.ex (hunk 1 above)
Comment (lucca65) [reply lib/cambiatus_web/controllers/rich_link_controller.ex:93]: +1, this is not consistent at all in our contexts. I do think we need to aim for consistency

File: lib/cambiatus_web/controllers/rich_link_controller.ex (hunk 2 above)
Comment (lucca65) [reply lib/cambiatus_web/controllers/rich_link_controller.ex:118]: One thing to keep in mind is that community creation happens on the blockchain, and its synced up to our database. This means that we don't have the creators language at our context, unless we modify the contract to add this extra information. IMO, its not worth the trouble, at least for now. 

I mean, at some point we will need to walk you through contract modifications and how to respond to that in our backend. We have #148 that seems like a nice spot for this exercise

File: lib/cambiatus_web/controllers/rich_link_controller.ex [hunk 4]
```diff
@@ -7,31 +7,33 @@ defmodule CambiatusWeb.RichLinkController do
...
 
-  alias CambiatusWeb.Resolvers.{Accounts, Commune, Shop}
+  alias CambiatusWeb.Resolvers.{Accounts, Shop}
   alias Cambiatus.Repo
 
   @fallback_image "https://cambiatus-uploads.s3.amazonaws.com/cambiatus-uploads/b214c106482a46ad89f3272761d3f5b5"
 
   def rich_link(conn, params) do
     language = get_req_header(conn, "accept-language")
+    context = conn.private[:absinthe][:context]
```
Comment (lucca65) [inline lib/cambiatus_web/controllers/rich_link_controller.ex:17]: This don't make sense, absinthe context is relevant when we receive GraphQL over HTTP requests. Controllers don't handle that. 

Remember that we have two APIs on our backend today: GraphQL and Rest. We should consider them completely separate.

**Review by lucca65 — CHANGES_REQUESTED** [review]
I think we got the wrong concept here on this issue bro. We don't have community information over HTTP Rest, only given our graphql Stuff. 

Think about it. The GraphQL client is the frontend, but the user of our Rich Link is the scrapping bots and Apps previewers. They don't do that using GraphQL, but rather plain json/http. 

Unless I'm missing something this is not going to fix it for our rich link use cases

File: lib/cambiatus_web/controllers/rich_link_controller.ex (hunk 4 above)
Comment (MatheusBuss) [reply lib/cambiatus_web/controllers/rich_link_controller.ex:17]: Oops, forgot about that, sorry. It was just bothering me that the community is already stored in memory and the controller had to fetch it again.

I did some refactoring to place the current community also into conn itself, this way it's not reliant on GraphQL. But this does imply in having the same information passing around the app twice on every call.

File: lib/cambiatus_web/controllers/rich_link_controller.ex (hunk 2 above)
Comment (MatheusBuss) [reply lib/cambiatus_web/controllers/rich_link_controller.ex:117]: My idea for this case was to get the user from the creator field in the Community struct and use this language. It's not perfect, but it's something

File: lib/cambiatus_web/controllers/rich_link_controller.ex (hunk 1 above)
Comment (MatheusBuss) [reply lib/cambiatus_web/controllers/rich_link_controller.ex]: :heavy_check_mark: Done

**Review by lucca65 — APPROVED** [review]
✅
